const mongoose = require("mongoose");
const passportLocalMongoosePkg = require("passport-local-mongoose");
const passportLocalMongoose =
  passportLocalMongoosePkg.default || passportLocalMongoosePkg;

const lawyerSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true
    },
    BarCouncilRegistrationNumber: {
      type: Number,
      required: true,
      unique: true
    }
  },
  { timestamps: true }
);

// Use default username (auto-generated by passport-local-mongoose)
lawyerSchema.plugin(passportLocalMongoose);

module.exports = mongoose.model("Lawyer", lawyerSchema);
